var USER_CONFIG = {
	heng:{
		"55":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:1050}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:0},//文字上
				},
				"role":{
					scale:1,
					offset:{x:100,y:350},//人
				}
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:1050}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:50},//文字上
				},
				"role":{
					scale:1,
					offset:{x:100,y:350},//人
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1.2,
					offset:{x:0,y:900}
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:-100},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:-350},//文字上
				},
				"role":{
					scale:1.2,
					offset:{x:100,y:50},
				}
			},
			en:{
				"screen":{
					scale:1.2,
					offset:{x:0,y:900}
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:-100},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:-300},//文字上
				},
				"role":{
					scale:1.2,
					offset:{x:100,y:50},
				}
			}
		}
	},
	shu:{
		"55":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:650}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:0},//文字上
				},
				"role":{
					scale:1,
					offset:{x:100,y:350},//人
				}
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:650}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:50},//文字上
				},
				"role":{
					scale:1,
					offset:{x:100,y:350},//人
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1.2,
					offset:{x:0,y:500}
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:-100},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:-350},//文字上
				},
				"role":{
					scale:1.2,
					offset:{x:100,y:50},
				}
			},
			en:{
				"screen":{
					scale:1.2,
					offset:{x:0,y:500}
				},
				"labelUp":{
					scale:1,
					offset:{x:-100,y:-100},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:200,y:-300},//文字上
				},
				"role":{
					scale:1.2,
					offset:{x:100,y:50},
				}
			}
		}
	}
}

module.exports = {
	USER_CONFIG:USER_CONFIG,
};




