var USER_CONFIG = {
	heng:{
		"55":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:800}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板
				},
				"star":{
					scale:1,
					offset:{x:0,y:-0},//星
				}
				
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:800}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板
				},
				"star":{
					scale:1,
					offset:{x:0,y:-0},//星
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:700}
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:-100},
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:-330},
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-400},
				},
				"star":{
					scale:1,
					offset:{x:0,y:-350},//星
				}
				
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:700}
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:-100},
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:-330},
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-400},
				},
				"star":{
					scale:1,
					offset:{x:0,y:-450},//星
				}
			}
		}
	},
	shu:{
		"55":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:250}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板
				},
				"star":{
					scale:1,
					offset:{x:0,y:-0},//星
				}
				
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:250}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板
				},
				"star":{
					scale:1,
					offset:{x:0,y:-0},//星
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:0,y:200}
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:-100},
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:-330},
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-400},
				},
				"star":{
					scale:1,
					offset:{x:0,y:-350},//星
				}
				
			},
			en:{
				"screen":{
					scale:1,
					offset:{x:0,y:200}
				},
				"labelUp":{
					scale:1,
					offset:{x:0,y:-100},
				},
				"labelDown":{
					scale:1,
					offset:{x:0,y:-330},
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-400},
				},
				"star":{
					scale:1,
					offset:{x:0,y:-450},//星
				}
			}
		}
	},
}

module.exports = {
	USER_CONFIG:USER_CONFIG,
};




