var USER_CONFIG = {
	shu:{
		"55":{
			ch:{
				"screen_bottom":{
					scale:1,
					offset:{x:-30,y:600}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:600}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:80},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			},
			en:{
				"screen_bottom":{
					scale:1,
					offset:{x:-30,y:600}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:600}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:80},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			}
		},
		"65":{
			ch:{
				"screen_bottom":{
					scale:1,
					offset:{x:-30,y:800}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:800}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:140},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			},
			en:{
				"screen_bottom":{
					scale:1,
					offset:{x:-30,y:800}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:800}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:140},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			}
		}
		
	},
	heng:{
		"55":{
			ch:{
				"screen_bottom":{
					scale:0.8,
					offset:{x:0,y:1000}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:600}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:80},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			},
			en:{
				"screen_bottom":{
					scale:0.8,
					offset:{x:0,y:1000}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:600}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:80},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			}
		},
		"65":{
			ch:{
				"screen_bottom":{
					scale:0.8,
					offset:{x:0,y:1300}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:800}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:140},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			},
			en:{
				"screen_bottom":{
					scale:0.8,
					offset:{x:0,y:1300}//截图
				},
				"screen_top":{
					scale:1,
					offset:{x:70,y:800}//截图
				},
				"label":{
					scale:1,
					offset:{x:0,y:140},//文字
				},
				"role":{
					scale:1,
					offset:{x:0,y:0},//人物
				}
			}
		}
		
	}
}
module.exports = {
	USER_CONFIG:USER_CONFIG,
};




