var USER_CONFIG = {
	heng:{
		"55":{
			ch:{
				"screen":{
					scale:0.86,
					offset:{x:-330,y:379}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-300,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-300,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},

			},
			en:{
				"screen":{
					scale:0.86,
					offset:{x:-330,y:379}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-400,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-400,y:30},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:-450,y:379}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-300,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-300,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},

			},
			en:{
				"screen":{
					scale:1,
					offset:{x:-450,y:379}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-400,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-400,y:30},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
			}
		}
	},
	shu:{
		"55":{
			ch:{
				"screen":{
					scale:0.86,
					offset:{x:-330,y:250}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-300,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-300,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},

			},
			en:{
				"screen":{
					scale:0.86,
					offset:{x:-330,y:250}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-400,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-400,y:30},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:1,
					offset:{x:-450,y:200}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-300,y:300},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-300,y:80},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},

			},
			en:{
				"screen":{
					scale:1,
					offset:{x:-450,y:200}//截图
				},
				"labelUp":{
					scale:1,
					offset:{x:-400,y:250},//文字上
				},
				"labelDown":{
					scale:1,
					offset:{x:-400,y:30},//文字下
				},
				"bottom_bar":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
				"role":{
					scale:1,
					offset:{x:0,y:-0},//底板f
				},
			}
		}
	},

}

module.exports = {
	USER_CONFIG:USER_CONFIG,
};




