var USER_CONFIG = {
	//
	heng:{
		"55":{
			ch:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:940}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:0},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:0},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765}
				}
			},
			en:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:940}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:0},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765}
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:940+420}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:300},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765+410},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765+410}
				}
			},
			en:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:940+420}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:300},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765+410},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765+410}
				}
			}
		}
	},
	shu:{
		"55":{
			ch:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:600}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:0},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:0},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765}
				}
			},
			en:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:600}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:0},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:0},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765}
				}
			}
		},
		"65":{
			ch:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:600+420}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:0},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:300},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765+410},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765+410}
				}
			},
			en:{
				"screen":{
					scale:0.566,
					offset:{x:200,y:600+420}//截图
				},
				"label_up":{
					scale:1,
					offset:{x:0,y:300},//文字
				},
				"label_down":{
					scale:1,
					offset:{x:0,y:60},//文字
				},
				"bottom_label_bar":{
					scale:1,
					offset:{x:0,y:0},//文字
				},
				"role":{
					scale:1,
					offset:{x:-200,y:300},//人物
				},
				"decoration":{
					scale:1,
					offset:{x:200,y:765+410},//装饰物
				},
				"petal":{
					scale:1,
					offset:{x:0,y:600},//花瓣
				},
				"circle":{
					scale:1,
					offset:{x:0,y:765+410}
				}
			}
		}
	}
	
}
module.exports = {
	USER_CONFIG:USER_CONFIG,
};




